src/main/java/ua/softserveinc/tc/controller/user/BookingTimeController.java
src/main/java/ua/softserveinc/tc/service/BookingService.java
src/main/java/ua/softserveinc/tc/service/impl/BookingServiceImpl.java
src/main/webapp/WEB-INF/template/default/template.jsp
src/main/webapp/WEB-INF/views/common/index.jsp
src/main/webapp/resources/css/default.css
src/main/webapp/resources/js/Error.js
src/main/webapp/resources/js/userCalendar.js

Букінги для однієї і тої самої дитини, які пересікаються в часі тепер не додаються. В файлі error.js є функція на виклик error-box-а, який поки-шо можем всі юзати.

Fixed the booking duplication bug and added an error.js file

---

src/main/webapp/WEB-INF/views/common/index.jsp
src/main/webapp/resources/js/userCalendar.js

The booking data is validated when the Book button is clicked in the Create Booking dialog. Validation works only for single event booking.

Seliuchenko lvjavs 223 create booking dialog data validation

---

src/main/webapp/WEB-INF/views/common/index.jsp
src/main/webapp/resources/js/userCalendar.js

Reverts koldovsky/kids-room#10

Revert "Seliuchenko lvjavs 223 create booking dialog data validation"

---

src/main/webapp/WEB-INF/views/admin/edit-room.jsp
src/main/webapp/resources/js/adminRoomSearch.js

Rooms at admin page can be searched by city

Admin roooms added search

---

src/main/java/ua/softserveinc/tc/dao/impl/RoomDaoImpl.java
src/main/java/ua/softserveinc/tc/service/impl/BookingServiceImpl.java
src/main/java/ua/softserveinc/tc/service/impl/RoomServiceImpl.java
src/main/webapp/resources/js/renderCalendar.js
src/main/webapp/resources/js/userCalendar.js

I have fixed 3 bugs. Please check it. 
LVJAVS-456 http://ssu-jira.softserveinc.com/browse/LVJAVS-456
LVJAVS-457 http://ssu-jira.softserveinc.com/browse/LVJAVS-457
LVJAVS-459 http://ssu-jira.softserveinc.com/browse/LVJAVS-459

Fixed bug LVJAVS-456, LVJAVS-457, LVJAVS-459

---

src/main/java/ua/softserveinc/tc/constants/ValidationConstants.java
src/main/java/ua/softserveinc/tc/dao/impl/UserDaoImpl.java
src/test/java/ua/softserveinc/tc/validator/EmailValidatorTest.java

Have added junit tests for email validation and changed email regex validator.

LVJAVS-362_Crash system when enter invalid email

---

src/main/java/ua/softserveinc/tc/service/impl/BookingServiceImpl.java
src/main/java/ua/softserveinc/tc/service/impl/RoomServiceImpl.java
src/main/webapp/WEB-INF/template/default/header.jsp
src/main/webapp/WEB-INF/views/manager/edit-booking.jsp
src/main/webapp/resources/css/edit-booking.css
src/main/webapp/resources/js/edit-booking.js
src/main/webapp/resources/js/tab-highlighting.js
src/main/webapp/resources/js/userCalendar.js

I have fixed bug LVJAVS-569. Please look at it.
http://ssu-jira.softserveinc.com/browse/LVJAVS-569

Lvjavs 569 problem with tabulation

---

src/main/webapp/resources/js/manager-create-events-validator.js

fixed bug with empty event title,

LVJAVS-597 

---

src/main/webapp/resources/js/edit-booking.js

have fixed  http://ssu-jira.softserveinc.com/browse/LVJAVS-583
hide modal window when press No button.

LVJAVS-583

---

src/main/webapp/WEB-INF/views/manager/edit-booking.jsp
src/main/webapp/resources/css/edit-booking.css
src/main/webapp/resources/js/edit-booking.js

LVJAVS-570 Incorrect alighnment of lables

---

src/main/java/ua/softserveinc/tc/dao/BookingDao.java
src/main/java/ua/softserveinc/tc/dao/impl/BookingDaoImpl.java
src/main/java/ua/softserveinc/tc/service/impl/BookingServiceImpl.java

Bug fixing http://ssu-jira.softserveinc.com/browse/LVJAVS-596
the function getBookings(Date startDate, Date endDate, User user, Room room, BookingState... bookingStates) add one day for including last day in parent report, and that is the reason why the bookings were duplicated, I`ve created new function to solve this problem.

LVJAVS-596

---

src/main/resources/properties/messages.properties
src/main/resources/properties/messages_ua.properties
src/main/webapp/WEB-INF/views/manager/edit-booking.jsp
src/main/webapp/resources/css/edit-booking.css
src/main/webapp/resources/js/edit-booking.js
src/main/webapp/resources/js/lib/messages-ua.js
src/main/webapp/resources/js/lib/messages.js

Add localization, Please check

Add localization in edit-booking form

---

src/main/resources/properties/messages.properties
src/main/resources/properties/messages_ua.properties
src/main/webapp/WEB-INF/views/common/index.jsp
src/main/webapp/resources/css/flow-form.css

In the pop-up message appeared: "This is one appointment in a series. What would you like to open?''

Edit event pop-up message

---

src/main/webapp/WEB-INF/views/user/my-bookings.jsp
src/main/webapp/resources/js/myBookings.js
src/main/webapp/resources/js/validation-my-booking.js

I've tried to use more JQuery in date validation.

Lvjavs 442

---

src/main/java/ua/softserveinc/tc/controller/manager/BookingEditController.java
src/main/java/ua/softserveinc/tc/controller/manager/ReportAllController.java
src/main/java/ua/softserveinc/tc/controller/manager/ReportParentController.java
src/main/java/ua/softserveinc/tc/dao/BookingDao.java
src/main/java/ua/softserveinc/tc/dao/impl/BookingDaoImpl.java
src/main/java/ua/softserveinc/tc/service/BookingService.java
src/main/java/ua/softserveinc/tc/service/impl/BookingServiceImpl.java

have avoided code duplication.  
add boolean parameter to method getBookings, 
deleted additional getBookings method from DAO.

Lvjavs 596 avoid duplication

---

src/main/resources/properties/messages.properties
src/main/resources/properties/messages_ua.properties
src/main/webapp/WEB-INF/views/user/edit-my-kid.jsp
src/main/webapp/resources/css/registerkid.css
src/main/webapp/resources/js/edit-my-kid.js

Add 'Cancel' button on ‘Edit your kid's info’ page

cancel button on edit kid

---

src/main/webapp/WEB-INF/template/default/template.jsp
src/main/webapp/WEB-INF/views/user/edit-my-kid.jsp
src/main/webapp/resources/js/constants/general_constants.js
src/main/webapp/resources/js/lib/messages-ua.js
src/main/webapp/resources/js/lib/messages.js
src/main/webapp/resources/js/validation-edit-kid.js

have fixed bug with validation update kids form on frontend and add constants file

LVJAVS-449 fixed validation on kids edit form

---

src/main/resources/properties/messages.properties
src/main/webapp/WEB-INF/template/default/template.jsp
src/main/webapp/resources/css/registerkid.css

I've fixed this bug
1. Go to https://kids-room-ua.herokuapp.com/
2. Login as a Parent (e.g. SSO: 'User Name' = "kidsroomuser"; 'Password' = "useruser")
3. Click on 'My kids' tab
4. Click on a kid on 'My kids' page
5. Click on 'Edit' button
6. Click on 'Take your kid's page off the list' link
Bootstap and jquery library were included in wrong order.  and bootstrap elements was able to override jquery elements

Lvjavs 451 

---

src/main/java/ua/softserveinc/tc/controller/admin/EditRoomController.java
src/main/java/ua/softserveinc/tc/service/RoomService.java
src/main/java/ua/softserveinc/tc/service/impl/RoomServiceImpl.java
src/main/resources/properties/messages.properties
src/main/resources/properties/messages_ua.properties
src/main/webapp/WEB-INF/views/admin/edit-room.jsp
src/main/webapp/resources/js/admin-deactivate-room-button.js
src/main/webapp/resources/js/edit-booking.js
src/main/webapp/resources/js/lib/messages-ua.js
src/main/webapp/resources/js/lib/messages.js

Administrator can deactivate room which has future events and bookings
Preconditions:
http://kids-room-ua.herokuapp.com/ is available
Room with bookings and events in the future is created
Steps to reproduce:
1. Log In as administrator (login: admin@softserveinc.com password: admin)
2. Go to 'Rooms list' page
3. Select room with events and bookings in the future
4. Click on green checkmark in 'Active/Inactive' column
5. Click 'OK' button in pop-up.
Expected result:
Error message:" Room cannot be inactive, when it has events and bookings that take place in the future. Please contact manager."
Actual result:
Room is deactivated

Administrator can deactivate room when there are the future bookings

---

src/main/java/ua/softserveinc/tc/constants/ImageConstants.java
src/main/java/ua/softserveinc/tc/constants/ReportConstants.java
src/main/java/ua/softserveinc/tc/constants/UserConstants.java
src/main/java/ua/softserveinc/tc/controller/util/UserChangePasswordController.java
src/main/java/ua/softserveinc/tc/controller/util/UserRegistrationController.java
src/main/java/ua/softserveinc/tc/util/ImagesHolderUtil.java
src/main/resources/properties/messages.properties
src/main/resources/properties/messages_ua.properties
src/main/webapp/WEB-INF/views/authorization/password-update.jsp

For demo branch

---

src/main/java/ua/softserveinc/tc/service/impl/CalendarServiceImpl.java
src/main/webapp/resources/js/constants/messages-ua.js
src/main/webapp/resources/js/constants/messages.js
src/main/webapp/resources/js/renderCalendar.js
src/main/webapp/resources/js/validation/manager-create-events-validator.js

editing events, improvements in creating events

editingEvents

---

src/main/java/ua/softserveinc/tc/constants/BookingConstants.java
src/main/java/ua/softserveinc/tc/controller/user/CRUDBookingsController.java
src/main/java/ua/softserveinc/tc/controller/user/CreateUpdateBookingsController.java
src/main/java/ua/softserveinc/tc/dao/BookingDao.java
src/main/java/ua/softserveinc/tc/dao/impl/BookingDaoImpl.java
src/main/java/ua/softserveinc/tc/service/BookingService.java
src/main/java/ua/softserveinc/tc/service/impl/BookingServiceImpl.java
src/main/java/ua/softserveinc/tc/validator/BookingValidator.java
src/main/java/ua/softserveinc/tc/validator/BookingValidatorImpl.java
src/main/java/ua/softserveinc/tc/validator/RecurrentBookingValidator.java
src/main/java/ua/softserveinc/tc/validator/RecurrentBookingValidatorImpl.java
src/main/webapp/resources/js/userCalendar.js

LVJAVS-683 - http://ssu-jira.softserveinc.com/browse/LVJAVS-683
LVJAVS-725 - http://ssu-jira.softserveinc.com/browse/LVJAVS-725

Rewritten algorithms for cancelling recurrent and plain bookings

---

src/main/java/ua/softserveinc/tc/controller/user/CRUDBookingsController.java
src/main/java/ua/softserveinc/tc/controller/user/EditMyKidPageController.java
src/main/java/ua/softserveinc/tc/controller/util/ExceptionHandlingControllerAdvice.java
src/main/java/ua/softserveinc/tc/dao/impl/BookingDaoImpl.java
src/main/java/ua/softserveinc/tc/service/impl/BookingServiceImpl.java

Micro refactoring before offering. Adding logs for ExceptionHandlerAdvice

Micro refactoring

---

src/main/java/ua/softserveinc/tc/controller/manager/BookingEditController.java
src/main/webapp/WEB-INF/template/default/header.jsp
src/main/webapp/WEB-INF/views/common/index.jsp
src/main/webapp/WEB-INF/views/manager/edit-booking.jsp
src/main/webapp/resources/js/edit-booking.js
src/main/webapp/resources/js/userCalendar.js

have fixed bugs
http://ssu-jira.softserveinc.com/browse/LVJAVS-757
http://ssu-jira.softserveinc.com/browse/LVJAVS-761
http://ssu-jira.softserveinc.com/browse/LVJAVS-762
http://ssu-jira.softserveinc.com/browse/LVJAVS-758

Lvjavs 761 758 757 762

---

src/main/java/ua/softserveinc/tc/constants/BookingConstants.java
src/main/java/ua/softserveinc/tc/controller/manager/BookingEditController.java
src/main/java/ua/softserveinc/tc/controller/user/CRUDBookingsController.java
src/main/java/ua/softserveinc/tc/dao/BookingDao.java
src/main/java/ua/softserveinc/tc/dto/BookingDto.java
src/main/java/ua/softserveinc/tc/service/BookingService.java
src/main/java/ua/softserveinc/tc/service/impl/BookingServiceImpl.java
src/main/webapp/resources/js/bookedkids.js
src/main/webapp/resources/js/constants/messages-ua.js
src/main/webapp/resources/js/constants/messages.js
src/main/webapp/resources/js/edit-booking.js
src/main/webapp/resources/js/userCalendar.js

LVJAVS-720 -http://ssu-jira.softserveinc.com/browse/LVJAVS-720
LVJAVS-721 - http://ssu-jira.softserveinc.com/browse/LVJAVS-721
LVJAVS-724 - http://ssu-jira.softserveinc.com/browse/LVJAVS-724

Rewritten algorithm for updating plain bookings. Resolved all bugs related to it.

---

pom.xml
src/main/java/ua/softserveinc/tc/dto/BookingDto.java
src/main/java/ua/softserveinc/tc/service/impl/BookingServiceImpl.java
src/main/java/ua/softserveinc/tc/validator/BookingValidatorImpl.java
src/test/java/ua/softserveinc/tc/validator/BookingValidatorTest.java
src/test/java/ua/softserveinc/tc/validator/EventValidatorTest.java

LVJAVS-816 - http://ssu-jira.softserveinc.com/browse/LVJAVS-816
LVJAVS-825 - http://ssu-jira.softserveinc.com/browse/LVJAVS-825

Fix bug LVJAVS-816. Finished Unit test for BookingValidator

---

src/main/java/ua/softserveinc/tc/controller/manager/BookingEditController.java
src/main/java/ua/softserveinc/tc/controller/manager/ConfirmBookingController.java
src/main/java/ua/softserveinc/tc/dao/BookingDao.java
src/main/webapp/resources/js/edit-booking.js
src/main/webapp/resources/js/header-manager.js

Fix bug with number of active bookings

LVJAVS-748

---

src/main/java/ua/softserveinc/tc/controller/admin/DayOffController.java
src/main/java/ua/softserveinc/tc/dao/DayOffDao.java
src/main/java/ua/softserveinc/tc/dao/impl/DayOffDaoImpl.java
src/main/java/ua/softserveinc/tc/service/DayOffService.java
src/main/java/ua/softserveinc/tc/service/impl/DayOffServiceImpl.java
src/test/java/ua/softserveinc/tc/repo/DayOffRepositoryTestIT.java

Now admin can create dayoffs with similar names and dates

Dayoff bug fixing

---

src/main/java/ua/softserveinc/tc/dto/BookingDto.java
src/test/java/ua/softserveinc/tc/dto/BookingDtoTest.java
src/test/java/ua/softserveinc/tc/validator/EmailValidatorTest.java

LVJAVS-933 - http://ssu-jira.softserveinc.com/browse/LVJAVS-933

Unit tests for BookingDto class

---

src/main/java/ua/softserveinc/tc/constants/ManagerConstants.java
src/main/java/ua/softserveinc/tc/controller/manager/ManagerMappingController.java
src/main/java/ua/softserveinc/tc/controller/manager/ViewEventController.java
src/main/webapp/resources/js/constants/messages.js
src/main/webapp/resources/js/validation/validation-edit-kid.js

There were some typo issues that I have fixed with this commit.Nothing haven't changed it all
Tasks: 
LVJAVS-751,
LVJAVS-447,
LVJAVS-805. 
You can find more information in Git Pull requests

FIX-typo-issues from the last sprint

---

src/main/java/ua/softserveinc/tc/controller/manager/BookingEditController.java
src/main/java/ua/softserveinc/tc/validator/TimeValidator.java
src/main/java/ua/softserveinc/tc/validator/TimeValidatorImpl.java
src/main/webapp/resources/js/edit-booking.js
src/main/webapp/resources/js/validation/validation-manager-booking-time.js
src/test/java/ua/softserveinc/tc/validator/TimeValidatorTest.java

Some part of changes is auto-changing tabs and spaces from my InteliJ.

LVJAVS-744: Fix issue of start booking date at 7:00

---

src/main/webapp/WEB-INF/views/manager/edit-booking.jsp

LVJAVS-853 fix bug with no window title while edit booking

---

src/main/webapp/resources/js/available-places-manager.js
src/main/webapp/resources/js/edit-booking.js

Add another level of aprove to manager booking page. And fixed bug when you can't finish the booking

Fixed Manager Booking

---

src/main/java/ua/softserveinc/tc/constants/AdminConstants.java
src/main/java/ua/softserveinc/tc/constants/MailConstants.java
src/main/java/ua/softserveinc/tc/constants/RoomConstants.java
src/main/java/ua/softserveinc/tc/controller/admin/EditRoomController.java
src/main/java/ua/softserveinc/tc/dao/BookingDao.java
src/main/java/ua/softserveinc/tc/dao/RoomDao.java
src/main/java/ua/softserveinc/tc/dao/impl/BookingDaoImpl.java
src/main/java/ua/softserveinc/tc/dao/impl/RoomDaoImpl.java
src/main/java/ua/softserveinc/tc/dto/DeactivateRoomDto.java
src/main/java/ua/softserveinc/tc/dto/InfoDeactivateRoomDto.java
src/main/java/ua/softserveinc/tc/service/MailService.java
src/main/java/ua/softserveinc/tc/service/RoomService.java
src/main/java/ua/softserveinc/tc/service/impl/MailServiceImpl.java
src/main/java/ua/softserveinc/tc/service/impl/RoomServiceImpl.java
src/main/resources/emailTemplates/deactivateRoom.vm
src/main/resources/properties/messages.properties
src/main/resources/properties/messages_ua.properties
src/main/webapp/WEB-INF/views/admin/edit-room.jsp
src/main/webapp/resources/css/admin-style.css
src/main/webapp/resources/js/admin-deactivate-room.js
src/main/webapp/resources/js/validation/validation-deactivate-room.js

about parents which have bookings in this room.

FIX-965: When admin deactivates room, email will be send with information 

---

src/main/java/ua/softserveinc/tc/controller/admin/AddManagerController.java
src/main/webapp/resources/css/edit-booking.css
src/main/webapp/resources/js/edit-booking.js

LVJAVS-821
Wrong 'Set arrival/leave time' buttons location repaired.

Lvjavs 821 wrong set arrival leave time buttons location

---

src/main/java/ua/softserveinc/tc/constants/DiscountConstants.java
src/main/java/ua/softserveinc/tc/controller/admin/restful/AdminDiscountController.java
src/main/java/ua/softserveinc/tc/dao/DayDiscountDao.java
src/main/java/ua/softserveinc/tc/dao/PersonlaDiscountDao.java
src/main/java/ua/softserveinc/tc/dao/impl/DayDiscountDaoImp.java
src/main/java/ua/softserveinc/tc/dao/impl/PersonalDiscountDaoImp.java
src/main/java/ua/softserveinc/tc/dto/PersonalDiscountDTO.java
src/main/java/ua/softserveinc/tc/entity/PersonalDiscount.java
src/main/java/ua/softserveinc/tc/entity/User.java
src/main/java/ua/softserveinc/tc/service/DayDiscountService.java
src/main/java/ua/softserveinc/tc/service/PersonalDiscountService.java
src/main/java/ua/softserveinc/tc/service/impl/DayDiscountServiceImpl.java
src/main/java/ua/softserveinc/tc/service/impl/PersonalDiscountServiceImpl.java
src/main/resources/import.sql

New method to get discount for period
New persistence level for personal discounts

DISCOUNT-IMPROVE2

---

src/main/webapp/resources/js/constants/general_constants.js

Only e-mails with @softserveinc.com are alowed.

LVJAVS-935

---

src/main/java/ua/softserveinc/tc/controller/admin/AddManagerController.java
src/main/webapp/WEB-INF/views/admin/edit-manager.jsp
src/main/webapp/resources/css/edit-booking.css
src/main/webapp/resources/js/constants/general_constants.js

Entering of phone number was fixed.
Also some unnecessary fields and styles was deleted.

LVJAVS-917

---

src/main/java/ua/softserveinc/tc/config/SecurityConfig.java
src/main/java/ua/softserveinc/tc/constants/TokenConstants.java
src/main/webapp/WEB-INF/views/authorization/login.jsp
src/main/webapp/resources/css/default.css
src/main/webapp/resources/css/edit-booking.css
src/main/webapp/resources/js/admin-add-manager.js
src/main/webapp/resources/js/lib/jquery.cookie.js
src/main/webapp/resources/js/validation/validation-login.js

LVJAVS-22
Added functionality for remember-me option
Last successfully logged in user is remembered if the 'Remember me' option was checked
Fix the view of picker from Lvjavs 821.
In the files, I've worked with corrected code view.

Lvjavs 22 remember me in login form

---

src/main/java/ua/softserveinc/tc/controller/util/UserController.java

Fixed bug when user can click 'back' button after login and see error  message

LVJAVS-888

---

src/main/webapp/resources/js/admin-add-manager.js
src/main/webapp/resources/js/available-places-manager.js
src/main/webapp/resources/js/edit-my-kid.js
src/main/webapp/resources/js/renderCalendar.js
src/main/webapp/resources/js/userCalendar.js

LVJAVS-894
Pop-up windows in application shouldn't allow resizing

LVJAVS-894

---

src/main/java/ua/softserveinc/tc/constants/ValidationConstants.java
src/main/java/ua/softserveinc/tc/controller/admin/AddManagerController.java
src/main/java/ua/softserveinc/tc/controller/admin/AdminMappingController.java
src/main/java/ua/softserveinc/tc/entity/ResponseWithErrors.java
src/main/java/ua/softserveinc/tc/service/UserService.java
src/main/java/ua/softserveinc/tc/service/impl/UserServiceImpl.java
src/main/resources/properties/messages.properties
src/main/webapp/resources/css/admin-style.css
src/main/webapp/resources/js/admin-add-manager.js

372 admin manager validation fixing

372 admin manager validation fixing

---

src/main/java/ua/softserveinc/tc/config/SecurityConfig.java
src/main/java/ua/softserveinc/tc/entity/RememberMeToken.java
src/main/webapp/resources/js/validation/validation-login.js

hibernate.hbm2ddl.auto = create
Please create new DB!

22 remember me token validity seconds
